---
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
notifications:
  email:
    on_success: always
    on_failure: always
script: make test
deploy:
  provider: pypi
  user: nrocco
  password:
    secure: lta1ytdoNfBXIaNApYGl5KWX6Eq8K6aptfYdv/MOWCpsGf0iq7hTyQnyfWPnYkqcgcqMXRkymSNrrvrulKe9evtV3XoEc9f5gOqJvicCdwXLpZjzwen6cUq0msfl0yD8Z4SV929CD6TT/5WmRufsNveLWLuau+rat7ocGVIX5RZmvU6HbD32Yb9pp361qT57WCt4raM1cjWTruqr3tF8QywokGsEkELr+VwpQfvwWTwtRl+ZvSgHhQM2Is3PsnL6ps9CIOW7W0TTkDG4dvDT2J/eldLC/Eo6FczvJPNs0teTSmz2YuEOrvROKtHebqsXE7e05NmVlCaAlR2xA8ea2rK/h9fAlDojqM4XnOBrEehSvjW4hOVTHZ7VZis+JXdjCTRYfr4eXJ1A8NnsflAadRlS3umTwhfh1qTvV/cWmR+xmli8WibfoR0cCHk9UMfdLjvURGsxML4p7r2P6J5KoZbn1hi3Tt1gZbv2JvlftiI3eWUU4DonVPLhQHG27WMoLOOjh+b2FrPktWazDpGIqVnAVzjLMcFlEz9o1DSD1iEYKUK0hreBxk5Ays/a5xxU+7YUrCYEdLle6wbAw21vyAhes90lOyfl1Y12heM2fkzQj1oj4zoaIU1TLPAnZXZVV2C19JU/qpyULkCYSZZQyGpgJQfbjkbInmWv8jn2RGs=
  on:
    tags: true
    branch: master
