[project]
name = "lswapi"
dynamic = ["version"]
description = "a python client library for easy leaseweb api access"
authors = [
    { name="Nico Di Rocco", email="n.dirocco@global.leaseweb.com" },
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">= 3.9"
dependencies = []

[project.urls]
Homepage = "http://developer.leaseweb.com"
Issues = "https://github.com/nrocco/lswapi"

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "requests-mock",
    "ruff",
]
httpie = [
    "httpie",
]
requests = [
    "requests",
]
aio = [
    "aiodns",
    "aiohttp",
]

[project.entry-points."httpie.plugins.auth.v1"]
httpie_lswapi = "lswapi.httpie:ApiAuthPlugin"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "src/",
    "pyproject.toml",
    "README.md",
]

[tool.hatch.version]
source = "vcs"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 999

[tool.ruff.lint]
ignore = ["E501"]  # E501 is the line-too-long rule
